### ISSUE TITLE
Trouble with categories.

### ISSUE THREAD

**Issue by HaoZeke** [kobus-v-schoor/dotgit#13]
Hi.

So my configs in common are not sourced when I try to use categories...

Given a folder structure like so:

```bash
| dotfiles
| --- common
| ----------- .zshrc
| ----------- .shell_promt.sh
| --- archLinux
| ----------- .zshSpecifics
| filelist
```

With filelist as:

```bash
# Common
.zshrc
.shell_prompt.sh

# Shell-related
.zshSpecifics:archLinux
```

When I run:

```bash
dotgit update
```

As expected, I only get the configs `.zshrc` and `.shell_prompt.sh`.

However when I run:

```bash
dotgit update archLinux
```

I only get `.zshSpecifics` instead of all 3 files.

My current workaround is to leverage category groups to define for example:

```bash
groupA = common,archLinux
```

Which then allows me to use:

```bash
dotgit update groupA
```

**Comment by kobus-v-schoor** [comment]
Hi,

This behaviour is intended - the "common" category is just another category and is just implicitly added when no categories are specified (along with your hostname). If you plan on using other categories than the default ones (common + hostname) frequently, I suggest you use category groups as you started doing. The cool thing is though you can leverage these category groups in such a way as to have them match your hostname, meaning you don't have to specify any categories when you run dotgit commands - see #7 for details

**Comment by kobus-v-schoor** [comment]
I just realised that I never updated the docs to include category groups - I added their syntax as well as an use-case which should clear things up
