### ISSUE TITLE
Broken Encryption

### ISSUE THREAD

**Issue by HaoZeke** [kobus-v-schoor/dotgit#14]
### Commands

```bash
# cryptlist contents
.zshrcB
# File path
dotfiles/common/.zshrcB
# Commands
dotgit verbose encrypt
```

### Expected

A binary encrypted file `.zshrcB` in `dotfiles/common/`

Output:

```bash
Initiating encryption

Initiating repo cleanup
Cleaning dotfiles folder
 > Removing common/.zshrcB
 > Removing empty directories
Cleaning dmz folder
 > Removing empty directories
```

I have setup a password using `dotgit passwd`

**Comment by kobus-v-schoor** [comment]
Hey @HaoZeke , I'm unable to replicate your problem - what I did:

```
dotgit init
echo foo > cryptlist
dotgit update
dotgit encrypt
```

"dotfiles" folder now contains:
```
dotfiles/
`-- common
    |-- foo
    `-- foo.hash

1 directory, 2 files
```

The file "foo" is correctly encrypted - I suspect you might've not run `dotgit update` before encrypting?

**Comment by HaoZeke** [comment]
Yup, running `dotgit update` before `dotgit encrypt` works perfectly!

Thanks a ton @kobus-v-schoor .
