### ISSUE TITLE
Project needs Quickstart guide

### ISSUE THREAD

**Issue by WnndGws** [kobus-v-schoor/dotgit#17]
This seems to solve many of my issues, but initial use was quite difficult. Can you confirm that I understand correctly?

- Situation 01: Have computer with dotfiles that need saving
    - Set up dotgit
    ```
    $ mkdir ~/dotgit
    $ cd ~/dotgit
    $ dotgit init
    ````
    - Edit `filelist` as per `$ dotgit help`
    - Set up dotgit password using `$ dotgit passwd`
    - Edit 'crytplist' as per `$ dotgit help`
    - Encrypt and update
    ```
    $ dotgit update (ctgs)
    $ dotgit encrypt
    $ dotgit generate
    ```

I have not dealt with these two yet
- Situation 02: Have computer where want copy dotfiles from dotgit
- Situation 03: Have edited dotfiles on Computer01 and want to copy them to Computer02

Thanks in advance! Project looks great so far

**Comment by kobus-v-schoor** [comment]
Hi @WnndGws, thanks for the suggestion - I've since made a new release of dotgit and I've added your suggestion to the readme file here https://github.com/kobus-v-schoor/dotgit#example-workflow.
