### ISSUE TITLE
dotgit deletes original config file when category is changed

### ISSUE THREAD

**Issue by anirvanmandal** [kobus-v-schoor/dotgit#18]
* I installed dot git then created a new dotfile repo in `~/src/dotfiles`
* Next I ran `dotgit init`

Next I updated the filelist to look like

```
~/.vimrc:config
```
Run dotgit update config

It symlinks the vimrc file to the PROJECT_ROOT/dofiles/config/ directory

Next lets edit the filelist once again

```
~/.vimrc:config1
```

Now if we run `dotgit update config1`

It deletes ~/.vimrc and PROJECT_ROOT/dotfiles/config/.vimrc. and does not create PROJECT_ROOT/dotfiles/config1/.vimrc

My expectation is that dotgit should in no case delete the original config file. Please let me know if I am doing something wrong.

**Comment by kobus-v-schoor** [comment]
Hi @anirvanmandal , thanks for opening the issue. I've since released a new version of dotgit with a test to verify specifically this case (which should now be fixed)
