### ISSUE TITLE
dotgit encrypt/decrypt doesn't restore unix permissions

### ISSUE THREAD

**Issue by ncoif** [kobus-v-schoor/dotgit#19]
Steps to reproduce:

- add and encrypt a file with non standard permissions (for example `~/.ssh/id_rsa.pub` with permissions 700)
- decrypt it and restore it on another computer
- the new file has default 755 unix permissions

What I was expecting:
- the new file has been restored with the same permissions as the original.

It seems that the problem is not impacting non-encrypted files, only files with encryptions.

**Comment by kobus-v-schoor** [comment]
Hi @ncoif, thanks for opening this issue - I realize it is a bit late to respond :) I've since released a new version of dotgit and this issue now has been fixed.
