### ISSUE TITLE
importlib.metadata.PackageNotFoundError: dotgit

### ISSUE THREAD

**Issue by hanckmann** [kobus-v-schoor/dotgit#28]
I have a runtime error using dotgit on Arch Linux (aur/dotgit 2.2.3-0)

```
$ dotgit restore linux
Traceback (most recent call last):
  File "/usr/bin/dotgit", line 33, in <module>
    sys.exit(load_entry_point('dotgit==2.2.3', 'console_scripts', 'dotgit')())
  File "/usr/bin/dotgit", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: dotgit
```

I have the latest Python 3.9 installed.

If I can help providing more info, please let me know...

**Comment by kobus-v-schoor** [comment]
Hi @hanckmann , thanks for reporting the issue - does this only happen when you run a restore operation or does this happen when you try to do anything with dotgit? Also, did you recently update to Python 3.9 (I'm not sure when Arch released the 3.9 version)?

**Comment by kobus-v-schoor** [comment]
@hanckmann I was able to reproduce the issue, seems the issue came in with updating Python from 3.8 -> 3.9, after re-installing dotgit from the AUR everything was working

**Comment by kobus-v-schoor** [comment]
I've made a new release (v2.2.8) which should trigger an update for all Arch users, this should hopefully resolve the issue for other users as well then
